package(default_visibility = ["//visibility:private"])

load("@io_bazel_stardoc//stardoc:stardoc.bzl", "stardoc")

stardoc(
    name = "reference",
    input = "//contest:defs.bzl",
    out = "reference.md",
)
