name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create an archive
        run: git archive --format tar.gz --prefix rules_contest-${RELEASE_VERSION}/ -o rules_contest-${RELEASE_VERSION}.tar.gz ${GITHUB_REF}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "rules_contest-${{ env.RELEASE_VERSION }}.tar.gz"
    env:
      RELEASE_VERSION: unknown
