name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "ubuntu-16.04"
          - "macos-latest"
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: "3.7.1"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build
        run: bazelisk build //...
      - name: Copy command.profile.gz
        run: cp "$(bazelisk info output_base)/command.profile.gz" ./
      - name: Upload command.profile.gz
        uses: actions/upload-artifact@v2
        with:
          name: command.profile.${{ matrix.os }}.gz
          path: command.profile.gz
      - name: Run tests
        run: bazelisk test --keep_going --test_strategy=exclusive --build_event_json_file=$PWD/build-events.jsonl //...
      - name: Render test reports
        run: bazelisk run //contest:render_test_results -- $PWD/build-events.jsonl
