name: test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "macos-latest"
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: "7.1.1"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build
        run: bazelisk build //...
      - name: Run unit tests
        run: bazelisk test --keep_going --test_strategy=exclusive //...
      - name: Run e2e tests
        run: bazelisk test --keep_going --test_strategy=exclusive --build_event_json_file=$PWD/build-events.jsonl //...
        working-directory: testmod
      - name: Render test reports
        run: bazelisk run @rules_contest//contest:render_test_results -- $PWD/build-events.jsonl
        working-directory: testmod
